import type { Task } from "@/lib/types"

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Repair damaged concrete on north section",
    description:
      "The concrete on the north section has cracks that need to be repaired before proceeding with the next phase.",
    priority: "high",
    assignee: "John Smith",
    deadline: "2025-05-25",
    status: "todo",
    photoUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "task-2",
    title: "Install temporary traffic signs",
    description: "Set up temporary traffic signs according to the traffic management plan.",
    priority: "medium",
    assignee: "Maria Garcia",
    deadline: "2025-05-22",
    status: "todo",
    photoUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "task-3",
    title: "Inspect drainage system",
    description: "Inspect the drainage system to ensure it meets specifications.",
    priority: "low",
    assignee: "David Chen",
    deadline: "2025-05-28",
    status: "todo",
  },
  {
    id: "task-4",
    title: "Order additional rebar materials",
    description: "We need more rebar for the next phase of construction.",
    priority: "medium",
    assignee: "John Smith",
    deadline: "2025-05-21",
    status: "todo",
  },
  {
    id: "task-5",
    title: "Clear debris from work area",
    description: "Remove all debris from the work area to prepare for the next phase.",
    priority: "high",
    assignee: "Maria Garcia",
    deadline: "2025-05-20",
    status: "todo",
  },
  {
    id: "task-6",
    title: "Excavate foundation for new section",
    description: "Begin excavation for the foundation of the new section according to the plans.",
    priority: "high",
    assignee: "David Chen",
    deadline: "2025-05-19",
    status: "in-progress",
    photoUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "task-7",
    title: "Test soil compaction",
    description: "Perform soil compaction tests to ensure it meets specifications.",
    priority: "medium",
    assignee: "John Smith",
    deadline: "2025-05-21",
    status: "in-progress",
  },
  {
    id: "task-8",
    title: "Update project timeline",
    description: "Update the project timeline based on current progress and any delays.",
    priority: "low",
    assignee: "Maria Garcia",
    deadline: "2025-05-22",
    status: "in-progress",
  },
  {
    id: "task-9",
    title: "Complete safety inspection",
    description: "Perform a comprehensive safety inspection of the site.",
    priority: "high",
    assignee: "David Chen",
    deadline: "2025-05-15",
    status: "done",
  },
  {
    id: "task-10",
    title: "Install temporary fencing",
    description: "Install temporary fencing around the perimeter of the work area.",
    priority: "medium",
    assignee: "John Smith",
    deadline: "2025-05-14",
    status: "done",
    photoUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "task-11",
    title: "Coordinate with utility companies",
    description: "Coordinate with utility companies for service relocations.",
    priority: "medium",
    assignee: "Maria Garcia",
    deadline: "2025-05-12",
    status: "done",
  },
  {
    id: "task-12",
    title: "Prepare weekly progress report",
    description: "Compile and submit the weekly progress report to the project manager.",
    priority: "low",
    assignee: "David Chen",
    deadline: "2025-05-17",
    status: "done",
  },
]
